trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/**
      - azresources/**
      - templates/**
      - scripts/**

variables:
  DEPLOY_FLAG: "YES"
  WORKING_DIR: $(System.DefaultWorkingDirectory)/azure-mono-deployment
  LOCATION: "centralus"

pr:
  branches:
    include:
      - master
  paths:
    include:
      - config/**
      - azresources/**
      - templates/**
      - scripts/**
      
stages:
  # Commercial Non-Production Subscription
  - stage: Deploy_COMMNP
    displayName: "Deploy Commercial Non-Production"
    condition: true
    jobs:
      - job: Detect_Changes
        displayName: "Detect Changed Files"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 2

          - script: |
              if [ "$(Build.Reason)" == "Manual" ] || [ "$(Build.Reason)" == "IndividualCI" ] || [ "$(Build.Reason)" == "BatchedCI" ]; then
                # For manual or CI builds, check what changed
                CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '(config/commnp-sub|azresources|templates|scripts)')
              else
                # For PR builds, compare with target branch
                git fetch origin $(System.PullRequest.TargetBranch)
                CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD | grep -E '(config/commnp-sub|azresources|templates|scripts)')
              fi
              
              if [ -n "$CHANGED_FILES" ]; then
                echo "Changes detected in relevant folders for commnp-sub"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"
                echo "$CHANGED_FILES"
              else
                echo "No changes detected in relevant folders for commnp-sub"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"  # Force deployment for testing
                echo "$CHANGED_FILES"
              fi
            name: changeDetection
            displayName: "Detect Changed Files"

      - job: Setup_Security_Groups
        displayName: "Set Up Security Groups"
        dependsOn: Detect_Changes
        condition: eq(dependencies.Detect_Changes.outputs['changeDetection.shouldDeploy'], 'true')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - template: templates/rbac-deployment-task.yml
            parameters:
              subscriptionName: "commnp-sub"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"
              location: $(LOCATION)

      - job: Deploy_Resources
        displayName: "Deploy Commercial Non-Prod Resources"
        dependsOn: Setup_Security_Groups
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - template: templates/master-subscription-template.yml
            parameters:
              subscriptionName: "commnp-sub"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"
              location: $(LOCATION)
              deployComponents:
                subscription: true
                resourceGroups: true
                network: true
                monitor: true
                backup: false
                recovery: false
  
  # New Project Deployment
  - stage: Deploy_NewProject
    displayName: "Deploy New Project"
    condition: true
    jobs:
      - job: Detect_Changes
        displayName: "Detect Changed Files"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 2

          - script: |
              if [ "$(Build.Reason)" == "Manual" ] || [ "$(Build.Reason)" == "IndividualCI" ] || [ "$(Build.Reason)" == "BatchedCI" ]; then
                # For manual or CI builds, check what changed
                CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '(config/new-project|azresources/modules/(main\.containerApps|main\.sqlServer|main\.managedEnvironment|main\.storageAccount|main\.nsg)\.bicep)')
              else
                # For PR builds, compare with target branch
                git fetch origin $(System.PullRequest.TargetBranch)
                CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD | grep -E '(config/new-project|azresources/modules/(main\.containerApps|main\.sqlServer|main\.managedEnvironment|main\.storageAccount|main\.nsg)\.bicep)')
              fi
              
              if [ -n "$CHANGED_FILES" ]; then
                echo "Changes detected in relevant folders for new-project"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"
                echo "$CHANGED_FILES"
              else
                echo "No changes detected in relevant folders for new-project"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"  # Changed from 'false' to 'true' to force deployment
                echo "$CHANGED_FILES"
              fi
            name: changeDetection
            displayName: "Detect Changed Files"

      - job: Setup_Security_Groups
        displayName: "Set Up Security Groups"
        dependsOn: Detect_Changes
        condition: eq(dependencies.Detect_Changes.outputs['changeDetection.shouldDeploy'], 'true')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - template: templates/rbac-deployment-task.yml
            parameters:
              subscriptionName: "new-project"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"  # Using commnp-sub ID, update as needed
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"  # Using commnp-sub connection, update as needed
              location: $(LOCATION)

      - job: Deploy_Resources
        displayName: "Deploy New Project Resources"
        dependsOn: Setup_Security_Groups
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - template: templates/master-subscription-template.yml
            parameters:
              subscriptionName: "new-project"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"
              location: $(LOCATION)
              projectPath: 'config/new-project'
              modulesPath: 'azresources/modules'
              deployComponents:
                subscription: false
                resourceGroups: true
                network: false
                monitor: false
                backup: false
                recovery: false
                storageAccount: true
                sqlServer: true
                managedEnvironment: true
                containerApps: true
          
  # # Commercial Production Subscription
  # - stage: Deploy_COMMPROD
  #   displayName: "Deploy Commercial Production"
  #   condition: true
  #   jobs:
  #     - job: Detect_Changes
  #       displayName: "Detect Changed Files"
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #           fetchDepth: 2

  #         - script: |
  #             if [ "$(Build.Reason)" == "Manual" ] || [ "$(Build.Reason)" == "IndividualCI" ] || [ "$(Build.Reason)" == "BatchedCI" ]; then
  #               # For manual or CI builds, check what changed
  #               CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '(config/commprod-sub|azresources|templates|scripts)')
  #             else
  #               # For PR builds, compare with target branch
  #               git fetch origin $(System.PullRequest.TargetBranch)
  #               CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD | grep -E '(config/commprod-sub|azresources|templates|scripts)')
  #             fi
              
  #             if [ -n "$CHANGED_FILES" ]; then
  #               echo "Changes detected in relevant folders for commprod-sub"
  #               echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"
  #               echo "$CHANGED_FILES"
  #             else
  #               echo "No changes detected in relevant folders for commprod-sub"
  #               echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]false"
  #               echo "$CHANGED_FILES"
  #             fi
  #           name: changeDetection
  #           displayName: "Detect Changed Files"

  #     - job: Setup_Security_Groups
  #       displayName: "Set Up Security Groups"
  #       dependsOn: Detect_Changes
  #       condition: eq(dependencies.Detect_Changes.outputs['changeDetection.shouldDeploy'], 'true')
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #         - template: templates/rbac-deployment-task.yml
  #           parameters:
  #             subscriptionName: "commprod-sub"
  #             subscriptionId: "94010bcc-f819-44ae-8f50-9a69e46d6bb7"
  #             serviceConnectionId: "7ad47311-d1ac-47fe-8359-9a3d5dafef2e"
  #             location: $(LOCATION)

  #     - job: Deploy_Resources
  #       displayName: "Deploy Commercial Prod Resources"
  #       dependsOn: Setup_Security_Groups
  #       pool:
  #         vmImage: 'ubuntu-latest'
  #       steps:
  #         - checkout: self
  #         - template: templates/master-subscription-template.yml
  #           parameters:
  #             subscriptionName: "commprod-sub"
  #             subscriptionId: "94010bcc-f819-44ae-8f50-9a69e46d6bb7"
  #             serviceConnectionId: "7ad47311-d1ac-47fe-8359-9a3d5dafef2e"
  #             location: $(LOCATION)
  #             deployComponents:
  #               subscription: true
  #               resourceGroups: true
  #               network: true
  #               monitor: true
  #               backup: false
  #               recovery: false

  # Additional subscription stages can be added in a similar pattern