trigger:
  branches:
    include:
      - master
  paths:
    include:
      - config/ciam-project/project-infrastructure/**
      - azresources/modules/containerApps.bicep
      - azresources/modules/sqlServer.bicep
      - azresources/modules/nsg.bicep

variables:
  DEPLOY_FLAG: "YES"
  WORKING_DIR: "$(System.DefaultWorkingDirectory)"
  LOCATION: "centralus"

pr:
  branches:
    include:
      - master
  paths:
    include:
      - config/ciam-project/project-infrastructure/**
      - azresources/modules/containerApps.bicep
      - azresources/modules/sqlServer.bicep
      - azresources/modules/nsg.bicep

stages:
  - stage: Deploy_CIAM
    displayName: "Deploy CIAM Project"
    jobs:
      - job: Detect_Changes
        displayName: "Detect Changed Files"
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            fetchDepth: 2

          - script: |
              echo "Current directory contents:"
              ls -la
              echo "Checking for changes..."
              if [ "$(Build.Reason)" == "Manual" ] || [ "$(Build.Reason)" == "IndividualCI" ] || [ "$(Build.Reason)" == "BatchedCI" ]; then
                # For manual or CI builds, check what changed
                CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep -E '(config/ciam-project/project-infrastructure|azresources/modules/(containerApps|sqlServer|nsg)\.bicep)')
              else
                # For PR builds, compare with target branch
                git fetch origin $(System.PullRequest.TargetBranch)
                CHANGED_FILES=$(git diff --name-only FETCH_HEAD HEAD | grep -E '(config/ciam-project/project-infrastructure|azresources/modules/(containerApps|sqlServer|nsg)\.bicep)')
              fi
              
              if [ -n "$CHANGED_FILES" ]; then
                echo "Changes detected in CIAM project files:"
                echo "$CHANGED_FILES"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]true"
              else
                echo "No changes detected in CIAM project files"
                echo "##vso[task.setvariable variable=shouldDeploy;isOutput=true]false"
              fi
            name: changeDetection
            displayName: "Detect Changed Files"

      - job: Deploy_CIAM_Resources
        displayName: "Deploy CIAM Resources"
        dependsOn: Detect_Changes
        condition: eq(dependencies.Detect_Changes.outputs['changeDetection.shouldDeploy'], 'true')
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          
          # Set up security groups first
          - template: ../../templates/rbac-deployment-task.yml
            parameters:
              subscriptionName: "commnp-sub"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"
              location: $(LOCATION)

          # Deploy CIAM resources using the master template
          - template: ../../templates/master-subscription-template.yml
            parameters:
              subscriptionName: "commnp-sub"
              subscriptionId: "921fd8cb-0c80-44cf-9fd5-2a7c8f2f8674"
              serviceConnectionId: "25f11d80-28be-4f01-b1f6-6e5bfb927671"
              location: $(LOCATION)
              deployComponents:
                subscription: false
                resourceGroups: true
                containerApps: true
                sqlServer: true
                nsg: true
                network: false
                monitor: false
                backup: false
                recovery: false
